spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  # drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days# 7 days

